export enum CollectionType {
  PAGES = "pages",
  FORMS = "forms",
  SLIDERS = "slider",
  REVIEWS = "reviews",
  REVIEWS_FILES = "reviews_files",
  SETTINGS = "globals",
  MENUS = "navigation",
  PRODUCTS = "products",
  OPTIONS = "options",
  USERS = "directus_users",
  BANNERS = "blocks_banner",
  CATEGORIES = "product_categories",
  FORM_SUBMISSIONS = "form_submissions",
  FAST_ORDERS = "fast_orders",
  CART = "cart",
  CART_ITEMS = "cart_item",
  CART_CART_ITEM = "cart_cart_item",
  FORM_SUBMISSION_VALUES = "form_submission_values",

  API_PRODUCTS = "/items/products",
  API_REVIEWS = "/items/reviews",

  PAGE_BLOCKS = "pages_blocks",
  BLOCKS_HERO = "blocks_hero",
  BLOCKS_BANNER = "blocks_banner_2",
  BLOCKS_REVIEWS = "blocks_reviews",
  BLOCKS_PRODUCTS_GRID = "blocks_products_grid",
  BLOCKS_RICH_TEXT_EDITOR = "blocks_rich_text_editor",
  BLOCKS_CATEGORIES_CAROUSEL = "blocks_categories_carousel",
}
